[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
"*" = ["models.yaml"]

[project]
name = "fabdata-llm"
version = "0.22.0-dev"
requires-python = ">=3.10, <3.13"
dependencies = [
    "pydantic == 2.*",
    "python-dotenv == 1.*",
    "openai == 1.52.*",
    "anthropic == 0.37.*",
    "tiktoken == 0.8.*",
    "pytest",
    "pytest-cov",
    "pytest-dotenv",
    "aiofiles == 23.1.*",
    "pillow",
    "numpy",
    "mistralai >= 0.1.0,<0.3",
    "pyyaml",
    "google-auth == 2.32.*"
]
