[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
"*" = ["models.yaml"]

[project]
name = "fabdata-llm"
version = "0.21.2"
requires-python = ">=3.10, <3.13"
dependencies = [
    "pydantic == 2.*",
    "python-dotenv == 1.*",
    "openai == 1.45.*",
    "anthropic == 0.26.*",
    "tiktoken == 0.7.*",
    "pytest == 7.2.*",
    "pytest-cov == 4.0.*",
    "pytest-dotenv == 0.5.*",
    "aiofiles == 23.1.*",
    "pillow == 9.5.*",
    "numpy == 1.26.*",
    "mistralai == 0.1.*",
    "pyyaml",
    "google-auth == 2.32.*"
]
